name: Deploy para VM

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Copiar arquivos para a VM via SSH
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_KEY }}
        source: "."
        target: "/var/www/meusite/app-teste-ci/"

    - name: Rodar comandos na VM
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_KEY }}
        script: |
          cd /var/www/meusite/app-teste-ci
          composer install --no-dev
          sudo systemctl reload nginx
